#' CV multivariate PLS (comparable to cv_unique)
#'
#' @param X a number-of-observations times nodes matrix.
#' @param Y a number-of-observations times reponses matrix.
#' @param ncomp number of components, integer.
#' @param center center the data.
#' @param folds a user defined list of folds (as generated by
#' caret::createFolds()) or an integer indicating the number of folds.
#' Independent of fdaPDE::FPCA.FEM's validation.
#' @param verbose logical, indicating if messages should be printed.
#'
#' @return A list of crossvalidates erros (CVEs).
#' @export
#'
#' @examples
#' # 1D example:
#'
#' # library(pls)
#' # library(fda)
#'
#' # Octane number:
#' Y <- as.matrix(pls::gasoline$octane)
#'
#' # Gasoline NIR spectra:
#' X <- as.matrix( as.data.frame( pls::gasoline$NIR ) )
#'
#' cv_mv <- cv_mvpls(X = X, Y = Y, ncomp = 5, folds = 5, center = TRUE,
#'                   verbose = FALSE)
#'
#' final_mv <-cv_mv$final_model
cv_mvpls <- function(X,
                     Y,
                     ncomp = min(10, ncol(X)),
                     center = TRUE,
                     folds = 5,
                     verbose = TRUE) {

  tictoc::tic("Crossvalidation")

  if (is.numeric(folds)) {

    num_folds <- folds
    folds <- caret::createFolds(Y, k = num_folds)

  }else if (is.list(folds)) {

    num_folds <- length(folds)

  }

  # Initialize MSEs:
  MSE_ncomp_fold <- matrix(data = NA,
                           nrow = ncomp,
                           ncol = num_folds) # MSE per component per fold
  colnames(MSE_ncomp_fold) <- paste0("fold_", 1:num_folds)
  rownames(MSE_ncomp_fold) <- paste0("ncomp_", 1:ncomp)


  for (ncomp_i in 1:ncomp) {

    if (verbose) {
      cat("Component ", ncomp_i, "/", ncomp, "\n")
    }


    for (i in 1:num_folds) {

      if(verbose){
        cat("  Fold ", i, "/", num_folds, "\n")}

      # build train
      Y_fold_train <- Y[-folds[[i]], , drop = F]
      X_fold_train <- X[-folds[[i]], , drop = F]

      # build test:
      Y_fold_test <- Y[folds[[i]], , drop = F]
      X_fold_test <- X[folds[[i]], , drop = F]

      # PLS model:
      pls_res <- pls::plsr(Y_fold_train ~ X_fold_train,
                           ncomp =  ncomp_i,
                           model = "oscorespls",
                           center = center )

      MSE_ncomp_fold[ncomp_i, i] <- mean( (as.numeric(Y_fold_test) -
                                             as.numeric(stats::predict(object = pls_res,
                                                                       newdata = X_fold_test,
                                                                       ncomp = ncomp_i) ))^2 )


    } # end k-fold


  } # loop in ncomp: number of components

  # Save the folds-averaged CV error:
  CVEs_ncomp <- rowMeans(MSE_ncomp_fold)
  names(CVEs_ncomp) <- paste0("ncomp_", 1:ncomp)

  if (verbose) {
    cat("Fitting final model\n")
  }

  final_model <- pls::plsr(Y ~ X,
                           ncomp =  ncomp,
                           method = "oscorespls",
                           center = TRUE,
                           scale = FALSE )

  ret <- list(CVEs_ncomp = CVEs_ncomp,
              MSE_ncomp_fold = MSE_ncomp_fold,
              final_model = final_model,
              elapsed = tictoc::toc(quiet = !verbose)    )

  return(ret)

}
